# --- Informações básicas da aplicação ---
spring.application.name=embalando-net-br
server.port=8080
spring.thymeleaf.encoding=UTF-8
spring.mvc.locale=pt_BR
spring.mvc.locale-resolver=fixed

# --- Configuração do Banco de Dados ---
spring.datasource.url=jdbc:mysql://mysql_embalando:3306/embalando?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=embalando
spring.datasource.password=embalando
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- Outras configs úteis (opcional, mas recomendado) ---
spring.jpa.properties.hibernate.format_sql=true
