# ================================
# PERFIL DEV - DOCKER
# ================================

spring.application.name=embalando-api
server.port=8080



# CONEXÃO COM MYSQL DENTRO DO CONTAINER (SERVIÇO mysql DO DOCKER-COMPOSE)
spring.datasource.url=jdbc:mysql://mysql:3306/embalando?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=embalando
spring.datasource.password=embalando_pwd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ACTUATOR (monitoramento)
management.endpoints.web.exposure.include=health,info
management.server.port=8081
management.endpoint.health.show-details=always
